version: "3.3"

services:

  traefik:
    image: "traefik:v2.0"
    container_name: "traefik"
    command:
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.certchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.certchallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.certchallenge.acme.email=hostmaster@unverified.email"
      - "--certificatesresolvers.certchallenge.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.certchallenge.acme.tlschallenge=false"
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - "/opt/unverified.email/traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  api:
    image: "${IMAGE_API}"
    container_name: "api"
    ports:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.secured.chain.middlewares=ssl-redirect,https-only"
      - "traefik.http.middlewares.https-only.redirectscheme.scheme=https"
      - "traefik.http.middlewares.ssl-redirect.headers.sslredirect=true"
      - "traefik.http.routers.api-unsecure.rule=Host(`api.unverified.email`)"
      - "traefik.http.routers.api-unsecure.middlewares=https-only"
      - "traefik.http.routers.api-unsecure.entrypoints=web"
      - "traefik.http.routers.api-secure.rule=Host(`api.unverified.email`)"
      - "traefik.http.routers.api-secure.middlewares=ssl-redirect"
      - "traefik.http.routers.api-secure.entrypoints=websecure"
      - "traefik.http.routers.api-secure.tls.certresolver=certchallenge"
    volumes:
      - type: volume
        source: mailbox-unverified
        target: /mailbox/unverified/
        read_only: true
        volume:
          nocopy: true

  smtpd:
    image: "${IMAGE_SMTPD}"
    container_name: "smtpd"
    ports:
      - "0.0.0.0:25:25"
    volumes:
      - type: volume
        source: "mailbox-unverified"
        target: "/mailbox/unverified/"
        read_only: false

volumes:
  mailbox-unverified:
