steps:
- label: Build and Test
  commands:
    - ./do test dist
    - rm -rf /tmp/artifacts/unverified.email/*
    - cp ./infra/api/dist/* /tmp/artifacts/unverified.email/
  plugins:
    - docker#v3.3.0:
        image: "haskell:8.6.5"
        mount-buildkite-agent: false
        volumes:
          - "${BUILD_CACHE_HASKELL_STACK}:/root/.stack:delegated"
          - "/tmp/artifacts/unverified.email/:/tmp/artifacts/unverified.email/:delegated"

- wait

- label: Container Images
  commands:
    - apk --no-cache add bash tar gzip git
    - mkdir -p ./infra/api/dist && cp /tmp/artifacts/unverified.email/* ./infra/api/dist/
    - ./do containers
  plugins:
    - docker#v3.3.0:
        image: "docker:latest"
        mount-buildkite-agent: false
        privileged: true
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/tmp/artifacts/unverified.email/:/tmp/artifacts/unverified.email/:ro"

- wait

- label: Publish
  commands:
    - ./do deploy
