steps:
- commands:
    - make test
    - make dist
    - rm -rf /tmp/artifacts/unverified.email/*
    - cp ./infra/api/dist/* /tmp/artifacts/unverified.email/
  label: Build and Test
  plugins:
    - docker#v3.3.0:
        image: "haskell:8.6.5"
        mount-buildkite-agent: false
        volumes:
          - "${BUILD_CACHE_HASKELL_STACK}:/root/.stack"
          - "/tmp/artifacts/unverified.email/:/tmp/artifacts/unverified.email/"

- wait

- commands:
    - apk --no-cache add make bash wget tar gzip
    - mkdir -p ./infra/api/dist && cp /tmp/artifacts/unverified.email/* ./infra/api/dist/
    - make containers
  label: Containers
  plugins:
    - docker#v3.3.0:
        image: "docker:latest"
        mount-buildkite-agent: false
        privileged: true
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/tmp/artifacts/unverified.email/:/tmp/artifacts/unverified.email/"

- wait

- commands:
    - apk --no-cache add make bash wget tar gzip openssh-client pv
    - make deploy
  label: Deploy
  plugins:
    - docker#v3.3.0:
        image: "docker:latest"
        mount-buildkite-agent: false
        privileged: true
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/tmp/artifacts/unverified.email/:/tmp/artifacts/unverified.email/"
