steps:
  - label: Build and Test
    commands:
      - stack build
      - stack test
    plugins:
      - docker#v3.3.0:
          image: "haskell:8.6.5"
          mount-buildkite-agent: false
          volumes:
            - "${BUILD_CACHE_HASKELL_STACK}:/root/.stack"
